### ISSUE TITLE
Issue #4: Data Retrieval Efficiency

### ISSUE THREAD

**Issue by chache3** [SunniJB/Project-A#4]
https://github.com/SunniJB/Project-A/blob/368761245cd3063929e25bfa771c0eb84d6cfa13/Project%20A/Assets/Scripts/SoundManager.cs#L18-L28

Severity: High
Description:
Currently, the method PlaySound iterates over a list to find a sound by its name. This approach could be inefficient, especially if the list grows in size.
Recommendation:
Consider using a more efficient data structure. Options include:

Dictionary: This would be the most straightforward change. Replace the List of `AudioClips` with a `Dictionary<string, AudioClip>`, where the key is the sound name. This allows O(1) lookup times.

Custom Struct: If more information is required per sound, a custom struct could be used alongside the dictionary. This struct could have the sound name, clip, and any other relevant information.

Sorted List: If you opt to keep the list, ensure it's sorted by the sound name and employ a binary search. This reduces the lookup time to O(log n).

**Comment by SunniJB** [comment]
I am not sure how to do this. We have covered dictionaries in class before, but it's a while ago and I've never had to use them. I don't know how to replace a list with a dictionary

**Comment by OzHache** [comment]
## Addressing Issue #4: Replacing a List with a Dictionary

### Introduction to Dictionaries:
A dictionary is a collection of key-value pairs where each unique key maps to a single value. In this case, the sound's name (string) would be the key, and the associated AudioClip would be the value.

### Steps to Implement the Dictionary:

1. **Declaration**:
   In addition to the `List<AudioClip> soundClips;` add:
   ```csharp
   private Dictionary<string, AudioClip> soundDictionary = new Dictionary<string, AudioClip>();
   ```

2. **Initialization**:
   Assuming that the `soundClips` list was populated via the Unity Editor, you'd need a method to transfer those clips into the dictionary. Add this to the `Start()` method:
   ```csharp
   foreach (var clip in soundClips)
   {
       soundDictionary[clip.name] = clip;
   }
   ```

3. **Accessing the Dictionary**:
   To play a sound using the dictionary, you no longer need to iterate through a list. Update the `PlaySound` method as follows:
   ```csharp
   public void PlaySound(string soundName)
   {
       if (soundDictionary.TryGetValue(soundName, out AudioClip clipToPlay))
       {
           audioSource.clip = clipToPlay;
           audioSource.Play();
       }
       else
       {
           Debug.LogWarning($"Sound with name {soundName} not found!");
       }
   }
   ```

   Here, the `TryGetValue` method attempts to get the value (the AudioClip) associated with the provided key (the sound's name). If it succeeds, it assigns that value to `clipToPlay` and proceeds with the rest of the method. If it fails, a warning is logged.

4. **Removing the Old List**:
   Now that the dictionary is doing the job, you might decide to remove the `List<AudioClip> soundClips`. However, if you're using it to populate sounds via the Unity Editor, you might keep it but make it a [SerializedField] private field to hide it from other scripts but still maintain the ability to edit it in the editor.

### Summary:
The advantage of using dictionaries over lists, in this case, is the speed of retrieval. With the list, you had a potential O(n) complexity for each sound play request, as you might have needed to scan through every sound. With the dictionary, it's approximately O(1) – near-instantaneous regardless of the number of sounds.

I hope this clears up the process of replacing a list with a dictionary. If any concept remains foggy or if you'd like a deep dive into any specific area, do give me a shout!

**Comment by SunniJB** [comment]
Thank you! I understand better now - when we covered dictionaries in school (which is over a year ago now) I bumbled with keys. For some reason I had the idea that they needed to be numbers. I've implemented your changes and they work!

**Comment by chache3** [comment]
Keys can be anything. They do not have to be numbers.
